### ISSUE TITLE
geoipupdate 2.5 not working 

### ISSUE THREAD

**Issue by nagpals** [maxmind/geoipupdate-legacy#90]
Hi,
I am on RHEL 7.4 (Maipo). My conf file looks like 

AccountID 0
LicenseKey 000000000000
#EditionIDs GeoLite2-Country  GeoLite2-City
ProductIds GeoLite2-Country GeoLite2-City

I get following error when i run geoipupdate : 

Downloading gzipped GeoIP Database...
Done
Updating /usr/share/GeoIP/GeoLite2-City.mmdb
Saving gzip file to /usr/share/GeoIP/GeoLite2-City.mmdb.gz ... download data to a gz file named /usr/share/GeoIP/GeoLite2-City.mmdb.gz
Done
Uncompressing gzip file ... Done
Performing sanity checks ... Database type is 1
database_info  FAIL null
Received Error -21 (Sanity check database_info string failed) when attempting to update GeoIP Database

Reading from other errors  people faced while running geoipupdate, i have tried with all version of geoipupdate available on my machine. I tried 
"which -a geoipupdate"

and received 
/bin/geoipupdate
/usr/bin/geoipupdate

I tried with both of them but still get the specified error. 

when my "GeoIP.conf" contains productids , it could download .dat files but never downloaded .mmdb files. 

I have spent two days rectifying this problem but failed to do so. Can you please help. 

FYI, i have downloaded geoipupdate from (2.5) : 
https://github.com/maxmind/geoipupdate/releases/tag/v2.5.0

**Comment by nagpals** [comment]
It was failing because of existing files, you can specify the new path by option "-d". It will work.

Thanks though.

**Comment by horgh** [comment]
It sounds like you resolved the problem, so that's great!

One thing I noticed that may help if you encounter further issues: The output you showed comes from a quite old version of geoipupdate. You can see the "Uncompressing" message being removed [in this old commit](https://github.com/maxmind/geoipupdate/commit/264f30a32da38a7869fcfd1475bc5974f410005a#diff-6fae46a85454e6b5e8c803fd5fe08264L462). You can check the version by running `geoipupdate -V`:

```
root@fe0503e59dd3:/will/code/geoipupdate# ./bin/geoipupdate -V
geoipupdate 2.5.0
```
